imports:
  - { resource: ../../../../src/Francisco/Shared/Infrastructure/Symfony/DependencyInjection/francisco_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Configure
  _instanceof:
    MN\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: [ 'mn.domain_event_subscriber' ]

  MN\Apps\Francisco\Backend\Controller\:
    resource: '../src/Controller'
    tags: [ 'controller.service_arguments' ]

  # Wire
  MN\Shared\:
    resource: '../../../../src/Shared'

  MN\Francisco\:
    resource: '../../../../src/Francisco'

  # -- TAGGING --
  MN\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [ !tagged mn.domain_event_subscriber ]
    lazy: true

  MN\Shared\Infrastructure\Bus\Event\DomainEventMapping:
    arguments: [ !tagged mn.domain_event_subscriber ]

  MN\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [ !tagged mn.database_connection ]

  MN\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  # -- APP DEFINITIONS --
  # Command/Query Handlers
  MN\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
    arguments: [ !tagged mn.command_handler ]

  MN\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
    arguments: [ !tagged mn.query_handler ]