framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  MN\Tests\:
    resource: '../../../../tests/src'

  # Instance selector
  MN\Shared\Domain\RandomNumberGenerator: '@MN\Tests\Shared\Infrastructure\ConstantRandomNumberGenerator'
  MN\Shared\Domain\Bus\Event\EventBus: '@MN\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus'