imports:
  - { resource: ../../../../src/Gabriel/Shared/Infrastructure/Symfony/DependencyInjection/gabriel_services.yml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Configure
  _instanceof:
    MN\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: [ 'mn.domain_event_subscriber' ]

  MN\Apps\Gabriel\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # Wire
  MN\Shared\:
    resource: '../../../../src/Shared'

  MN\Gabriel\:
    resource: '../../../../src/Gabriel'

  # -- TAGGING --
  MN\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [ !tagged mn.domain_event_subscriber ]
    lazy: true

  MN\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }